"""Development-only endpoints, active only with the mock video provider.

These exist so the *frontend* takes the same path in development as it will in
production: request a ticket, upload to the URL it names, then play back from
the grant it is given. A mock that only pretended would leave the real code
paths — upload progress, encoding states, the player — untested until the
VdoCipher account exists.

Uploads are kept in a temporary directory and served back, so the clip that
plays is the clip that was uploaded. Nothing here is reachable in production:
Settings refuses to start there on the mock provider, and main.py only mounts
this router when the mock is active.
"""

from __future__ import annotations

import re
import tempfile
from pathlib import Path
from typing import Annotated

from fastapi import APIRouter, File, Form, HTTPException, UploadFile, status
from fastapi.responses import FileResponse

router = APIRouter(prefix="/dev", tags=["dev"])

STORE = Path(tempfile.gettempdir()) / "lms-dev-video"
STORE.mkdir(parents=True, exist_ok=True)

# Video ids are generated by the mock provider, but this value reaches the
# filesystem, so it is validated rather than trusted: anything outside this
# character set could escape the directory.
SAFE_ID = re.compile(r"^[A-Za-z0-9_-]{1,64}$")

MAX_UPLOAD_BYTES = 2 * 1024 * 1024 * 1024


def _path_for(video_id: str) -> Path:
    if not SAFE_ID.match(video_id):
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="bad video id")
    return STORE / f"{video_id}.bin"


@router.post("/video-upload", status_code=status.HTTP_204_NO_CONTENT)
async def accept_mock_upload(
    video_id: Annotated[str, Form()],
    file: Annotated[UploadFile, File()],
) -> None:
    target = _path_for(video_id)
    written = 0
    # Streamed in chunks so a large clip never has to fit in memory.
    with target.open("wb") as handle:
        while chunk := await file.read(1024 * 1024):
            written += len(chunk)
            if written > MAX_UPLOAD_BYTES:
                handle.close()
                target.unlink(missing_ok=True)
                raise HTTPException(
                    status_code=status.HTTP_413_REQUEST_ENTITY_TOO_LARGE,
                    detail="file too large",
                )
            handle.write(chunk)


@router.get("/video/{video_id}")
async def serve_mock_video(video_id: str) -> FileResponse:
    """Play back an uploaded clip.

    FileResponse handles Range requests, which the <video> element needs in
    order to seek — without it the player can only stream from the start, and
    scrubbing silently does nothing.
    """
    path = _path_for(video_id)
    if not path.exists():
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="no such video")
    return FileResponse(path, media_type="video/mp4")
